dist: trusty

language: node_js
node_js: stable

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
jdk: openjdk11
sudo: required
cache:
    directories:
        ./angular/node_modules

before_install:
    #- jdk_switcher use openjdk11
    - java -version
    - chmod +x ./backend/mvnw
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - cd ./angular npm install
script:
    - cd ../backend/
    #- chmod a+x ./mvnw # moved up to before_install
    - ./mvnw -q clean install #package
    - ./mvnw spring-boot:run # java -jar target/*.jar
    - cd ../angular && npm run build
    - npm run e2e

# specify jobs
#jobs:
#  include:
#    - stage: backend
#      language: java
#      jdk: openjdk11
#      before_install: 
#        - cd ./backend/      
#      install: true
#      script: 
#        - mvn clean package # make a jar
#        #- java -jar target/*.jar # run jar - works but runs forever in job
#      cache:
#        directories:
#            - $HOME/.m2            
#    - stage: angular
#      language: node_js
#      node_js: stable
#      services:
#        - xvfb
#      before_install: 
#        - cd ./angular/
#      install: 
#        - npm install
#      script:
#        # - npm run build
#        # - npm start # refers to "start": "ng serve &" in package.json
#        # - protractor protractor.conf.js        
#        # - npm run test # 
#        - npm run e2e #
#      #before_script:
#        #- export DISPLAY=:99.0 # apparently not needed
#        #- sh -e /etc/init.d/xvfb start # xvfb moved up to "services"
#      cache:
#        directories:
#            - ./node_modules