# specify chrome to be used for e2e tests
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# specify jobs
jobs:
  include:
    - stage: backend
      language: java
      jdk: openjdk11
      before_install: 
        - cd ./backend/      
      install: true
      script: 
        - mvn clean package # make a jar
        - java -jar target/*.jar # run jar
      cache:
        directories:
            - $HOME/.m2            
    - stage: angular
      language: node_js
      node_js: stable
      services:
        - xvfb
      before_install: 
        - cd ./angular/
      install: 
        - npm install
      script:
        # - npm run build
        # - npm start # refers to "start": "ng serve &" in package.json
        # - protractor protractor.conf.js        
        # - npm run test # 
        - npm run e2e #
      #before_script:
        #- export DISPLAY=:99.0 # apparently not needed
        #- sh -e /etc/init.d/xvfb start # xvfb moved up to "services"
      cache:
        directories:
            - ./node_modules